provider: docker
major-version: 4
upstreamProviderOrg: kreuzwerker
aws: true
gcp: true
gcpRegistry: true
env:
  AWS_REGION: us-west-2
  ARM_CLIENT_ID: "30e520fa-12b4-4e21-b473-9426c5ac2e1e"
  ARM_SUBSCRIPTION_ID: "0282681f-7a9e-424b-80b2-96babd57a8a1"
  ARM_TENANT_ID: "706143bc-e1d4-4593-aee2-c9dc60ab9be7"
  ARM_CLIENT_SECRET: ${{ secrets.ARM_CLIENT_SECRET }}
  AZURE_LOCATION: westus
  DIGITALOCEAN_TOKEN: ${{ secrets.DIGITALOCEAN_TOKEN }}
  GOOGLE_CI_SERVICE_ACCOUNT_EMAIL: pulumi-ci@pulumi-ci-gcp-provider.iam.gserviceaccount.com
  GOOGLE_CI_WORKLOAD_IDENTITY_POOL: pulumi-ci
  GOOGLE_CI_WORKLOAD_IDENTITY_PROVIDER: pulumi-ci
  GOOGLE_PROJECT: pulumi-ci-gcp-provider
  GOOGLE_PROJECT_NUMBER: 895284651812
  GOOGLE_REGION: us-central1
  GOOGLE_ZONE: us-central1-a
  DOCKER_HUB_PASSWORD: ${{ secrets.DOCKER_HUB_PASSWORD }}
makeTemplate: bridged
docsCmd: "cd provider/pkg/docs-gen/examples/ && go run generate.go ./yaml ./"
hybrid: true
plugins:
  - name: terraform
    version: "1.0.16"
    kind: converter

  - name: aws
    version: "6.8.0"
team: ecosystem
actions:
  preTest:
    - name: Setup SSH key
      uses: webfactory/ssh-agent@v0.7.0
      with:
        ssh-private-key: ${{ secrets.PRIVATE_SSH_KEY_FOR_DIGITALOCEAN }}
pulumiConvert: 1
registryDocs: true
