comment:
  layout: "header, files, footer"
  hide_project_coverage: false

fixes:
  - "provider/v4/::provider/"

coverage:
  status:
    project:
      default:
        informational: true
    patch:
      default:
        informational: true
