// *** WARNING: this file was generated by pulumi-java-gen. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.docker.outputs;

import com.pulumi.core.annotations.CustomType;
import java.lang.String;
import java.util.Objects;

@CustomType
public final class ContainerLabel {
    private final String label;
    private final String value;

    @CustomType.Constructor
    private ContainerLabel(
        @CustomType.Parameter("label") String label,
        @CustomType.Parameter("value") String value) {
        this.label = label;
        this.value = value;
    }

    public String label() {
        return this.label;
    }
    public String value() {
        return this.value;
    }

    public static Builder builder() {
        return new Builder();
    }

    public static Builder builder(ContainerLabel defaults) {
        return new Builder(defaults);
    }

    public static final class Builder {
        private String label;
        private String value;

        public Builder() {
    	      // Empty
        }

        public Builder(ContainerLabel defaults) {
    	      Objects.requireNonNull(defaults);
    	      this.label = defaults.label;
    	      this.value = defaults.value;
        }

        public Builder label(String label) {
            this.label = Objects.requireNonNull(label);
            return this;
        }
        public Builder value(String value) {
            this.value = Objects.requireNonNull(value);
            return this;
        }        public ContainerLabel build() {
            return new ContainerLabel(label, value);
        }
    }
}
