// *** WARNING: this file was generated by pulumi-language-java. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.docker.outputs;

import com.pulumi.core.annotations.CustomType;
import com.pulumi.exceptions.MissingRequiredPropertyException;
import java.lang.Integer;
import java.lang.String;
import java.util.Objects;

@CustomType
public final class ContainerDeviceWriteBp {
    /**
     * @return The device path on the host, e.g. `/dev/sda`.
     * 
     */
    private String path;
    /**
     * @return The write rate limit in bytes per second.
     * 
     */
    private Integer rate;

    private ContainerDeviceWriteBp() {}
    /**
     * @return The device path on the host, e.g. `/dev/sda`.
     * 
     */
    public String path() {
        return this.path;
    }
    /**
     * @return The write rate limit in bytes per second.
     * 
     */
    public Integer rate() {
        return this.rate;
    }

    public static Builder builder() {
        return new Builder();
    }

    public static Builder builder(ContainerDeviceWriteBp defaults) {
        return new Builder(defaults);
    }
    @CustomType.Builder
    public static final class Builder {
        private String path;
        private Integer rate;
        public Builder() {}
        public Builder(ContainerDeviceWriteBp defaults) {
    	      Objects.requireNonNull(defaults);
    	      this.path = defaults.path;
    	      this.rate = defaults.rate;
        }

        @CustomType.Setter
        public Builder path(String path) {
            if (path == null) {
              throw new MissingRequiredPropertyException("ContainerDeviceWriteBp", "path");
            }
            this.path = path;
            return this;
        }
        @CustomType.Setter
        public Builder rate(Integer rate) {
            if (rate == null) {
              throw new MissingRequiredPropertyException("ContainerDeviceWriteBp", "rate");
            }
            this.rate = rate;
            return this;
        }
        public ContainerDeviceWriteBp build() {
            final var _resultValue = new ContainerDeviceWriteBp();
            _resultValue.path = path;
            _resultValue.rate = rate;
            return _resultValue;
        }
    }
}
