// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Docker.Buildx.Inputs
{

    public sealed class ManifestArgs : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// The SHA256 digest of the manifest.
        /// </summary>
        [Input("digest", required: true)]
        public Input<string> Digest { get; set; } = null!;

        /// <summary>
        /// The manifest's platform.
        /// </summary>
        [Input("platform", required: true)]
        public Input<Inputs.ManifestPlatformArgs> Platform { get; set; } = null!;

        /// <summary>
        /// The manifest's canonical ref.
        /// </summary>
        [Input("ref", required: true)]
        public Input<string> Ref { get; set; } = null!;

        /// <summary>
        /// The size of the manifest in bytes.
        /// </summary>
        [Input("size", required: true)]
        public Input<int> Size { get; set; } = null!;

        public ManifestArgs()
        {
        }
        public static new ManifestArgs Empty => new ManifestArgs();
    }
}
