// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Docker.Buildx.Inputs
{

    public sealed class SSHArgs : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// Useful for distinguishing different servers that are part of the same
        /// build.
        /// 
        /// A value of `default` is appropriate if only dealing with a single host.
        /// </summary>
        [Input("id", required: true)]
        public Input<string> Id { get; set; } = null!;

        [Input("paths")]
        private InputList<string>? _paths;

        /// <summary>
        /// SSH agent socket or private keys to expose to the build under the given
        /// identifier.
        /// 
        /// Defaults to `[$SSH_AUTH_SOCK]`.
        /// 
        /// Note that your keys are **not** automatically added when using an
        /// agent. Run `ssh-add -l` locally to confirm which public keys are
        /// visible to the agent; these will be exposed to your build.
        /// </summary>
        public InputList<string> Paths
        {
            get => _paths ?? (_paths = new InputList<string>());
            set => _paths = value;
        }

        public SSHArgs()
        {
        }
        public static new SSHArgs Empty => new SSHArgs();
    }
}
