// *** WARNING: this file was generated by pulumi-java-gen. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.docker.buildx.outputs;

import com.pulumi.core.annotations.CustomType;
import com.pulumi.docker.buildx.enums.CacheMode;
import com.pulumi.exceptions.MissingRequiredPropertyException;
import java.lang.Boolean;
import java.lang.String;
import java.util.Objects;
import java.util.Optional;
import javax.annotation.Nullable;

@CustomType
public final class CacheToAzureBlob {
    /**
     * @return Base URL of the storage account.
     * 
     */
    private @Nullable String accountUrl;
    /**
     * @return Ignore errors caused by failed cache exports.
     * 
     */
    private @Nullable Boolean ignoreError;
    /**
     * @return The cache mode to use. Defaults to `min`.
     * 
     */
    private @Nullable CacheMode mode;
    /**
     * @return The name of the cache image.
     * 
     */
    private String name;
    /**
     * @return Blob storage account key.
     * 
     */
    private @Nullable String secretAccessKey;

    private CacheToAzureBlob() {}
    /**
     * @return Base URL of the storage account.
     * 
     */
    public Optional<String> accountUrl() {
        return Optional.ofNullable(this.accountUrl);
    }
    /**
     * @return Ignore errors caused by failed cache exports.
     * 
     */
    public Optional<Boolean> ignoreError() {
        return Optional.ofNullable(this.ignoreError);
    }
    /**
     * @return The cache mode to use. Defaults to `min`.
     * 
     */
    public Optional<CacheMode> mode() {
        return Optional.ofNullable(this.mode);
    }
    /**
     * @return The name of the cache image.
     * 
     */
    public String name() {
        return this.name;
    }
    /**
     * @return Blob storage account key.
     * 
     */
    public Optional<String> secretAccessKey() {
        return Optional.ofNullable(this.secretAccessKey);
    }

    public static Builder builder() {
        return new Builder();
    }

    public static Builder builder(CacheToAzureBlob defaults) {
        return new Builder(defaults);
    }
    @CustomType.Builder
    public static final class Builder {
        private @Nullable String accountUrl;
        private @Nullable Boolean ignoreError;
        private @Nullable CacheMode mode;
        private String name;
        private @Nullable String secretAccessKey;
        public Builder() {}
        public Builder(CacheToAzureBlob defaults) {
    	      Objects.requireNonNull(defaults);
    	      this.accountUrl = defaults.accountUrl;
    	      this.ignoreError = defaults.ignoreError;
    	      this.mode = defaults.mode;
    	      this.name = defaults.name;
    	      this.secretAccessKey = defaults.secretAccessKey;
        }

        @CustomType.Setter
        public Builder accountUrl(@Nullable String accountUrl) {

            this.accountUrl = accountUrl;
            return this;
        }
        @CustomType.Setter
        public Builder ignoreError(@Nullable Boolean ignoreError) {

            this.ignoreError = ignoreError;
            return this;
        }
        @CustomType.Setter
        public Builder mode(@Nullable CacheMode mode) {

            this.mode = mode;
            return this;
        }
        @CustomType.Setter
        public Builder name(String name) {
            if (name == null) {
              throw new MissingRequiredPropertyException("CacheToAzureBlob", "name");
            }
            this.name = name;
            return this;
        }
        @CustomType.Setter
        public Builder secretAccessKey(@Nullable String secretAccessKey) {

            this.secretAccessKey = secretAccessKey;
            return this;
        }
        public CacheToAzureBlob build() {
            final var _resultValue = new CacheToAzureBlob();
            _resultValue.accountUrl = accountUrl;
            _resultValue.ignoreError = ignoreError;
            _resultValue.mode = mode;
            _resultValue.name = name;
            _resultValue.secretAccessKey = secretAccessKey;
            return _resultValue;
        }
    }
}
