// *** WARNING: this file was generated by pulumi-language-java. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.docker.inputs;

import com.pulumi.core.Output;
import com.pulumi.core.annotations.Import;
import com.pulumi.docker.inputs.ServiceTaskSpecResourcesReservationGenericResourcesArgs;
import java.lang.Integer;
import java.util.Objects;
import java.util.Optional;
import javax.annotation.Nullable;


public final class ServiceTaskSpecResourcesReservationArgs extends com.pulumi.resources.ResourceArgs {

    public static final ServiceTaskSpecResourcesReservationArgs Empty = new ServiceTaskSpecResourcesReservationArgs();

    /**
     * User-defined resources can be either Integer resources (e.g, `SSD=3`) or String resources (e.g, GPU=UUID1)
     * 
     */
    @Import(name="genericResources")
    private @Nullable Output<ServiceTaskSpecResourcesReservationGenericResourcesArgs> genericResources;

    /**
     * @return User-defined resources can be either Integer resources (e.g, `SSD=3`) or String resources (e.g, GPU=UUID1)
     * 
     */
    public Optional<Output<ServiceTaskSpecResourcesReservationGenericResourcesArgs>> genericResources() {
        return Optional.ofNullable(this.genericResources);
    }

    /**
     * The amounf of memory in bytes the container allocates
     * 
     */
    @Import(name="memoryBytes")
    private @Nullable Output<Integer> memoryBytes;

    /**
     * @return The amounf of memory in bytes the container allocates
     * 
     */
    public Optional<Output<Integer>> memoryBytes() {
        return Optional.ofNullable(this.memoryBytes);
    }

    /**
     * CPU shares in units of 1/1e9 (or 10^-9) of the CPU. Should be at least `1000000`
     * 
     */
    @Import(name="nanoCpus")
    private @Nullable Output<Integer> nanoCpus;

    /**
     * @return CPU shares in units of 1/1e9 (or 10^-9) of the CPU. Should be at least `1000000`
     * 
     */
    public Optional<Output<Integer>> nanoCpus() {
        return Optional.ofNullable(this.nanoCpus);
    }

    private ServiceTaskSpecResourcesReservationArgs() {}

    private ServiceTaskSpecResourcesReservationArgs(ServiceTaskSpecResourcesReservationArgs $) {
        this.genericResources = $.genericResources;
        this.memoryBytes = $.memoryBytes;
        this.nanoCpus = $.nanoCpus;
    }

    public static Builder builder() {
        return new Builder();
    }
    public static Builder builder(ServiceTaskSpecResourcesReservationArgs defaults) {
        return new Builder(defaults);
    }

    public static final class Builder {
        private ServiceTaskSpecResourcesReservationArgs $;

        public Builder() {
            $ = new ServiceTaskSpecResourcesReservationArgs();
        }

        public Builder(ServiceTaskSpecResourcesReservationArgs defaults) {
            $ = new ServiceTaskSpecResourcesReservationArgs(Objects.requireNonNull(defaults));
        }

        /**
         * @param genericResources User-defined resources can be either Integer resources (e.g, `SSD=3`) or String resources (e.g, GPU=UUID1)
         * 
         * @return builder
         * 
         */
        public Builder genericResources(@Nullable Output<ServiceTaskSpecResourcesReservationGenericResourcesArgs> genericResources) {
            $.genericResources = genericResources;
            return this;
        }

        /**
         * @param genericResources User-defined resources can be either Integer resources (e.g, `SSD=3`) or String resources (e.g, GPU=UUID1)
         * 
         * @return builder
         * 
         */
        public Builder genericResources(ServiceTaskSpecResourcesReservationGenericResourcesArgs genericResources) {
            return genericResources(Output.of(genericResources));
        }

        /**
         * @param memoryBytes The amounf of memory in bytes the container allocates
         * 
         * @return builder
         * 
         */
        public Builder memoryBytes(@Nullable Output<Integer> memoryBytes) {
            $.memoryBytes = memoryBytes;
            return this;
        }

        /**
         * @param memoryBytes The amounf of memory in bytes the container allocates
         * 
         * @return builder
         * 
         */
        public Builder memoryBytes(Integer memoryBytes) {
            return memoryBytes(Output.of(memoryBytes));
        }

        /**
         * @param nanoCpus CPU shares in units of 1/1e9 (or 10^-9) of the CPU. Should be at least `1000000`
         * 
         * @return builder
         * 
         */
        public Builder nanoCpus(@Nullable Output<Integer> nanoCpus) {
            $.nanoCpus = nanoCpus;
            return this;
        }

        /**
         * @param nanoCpus CPU shares in units of 1/1e9 (or 10^-9) of the CPU. Should be at least `1000000`
         * 
         * @return builder
         * 
         */
        public Builder nanoCpus(Integer nanoCpus) {
            return nanoCpus(Output.of(nanoCpus));
        }

        public ServiceTaskSpecResourcesReservationArgs build() {
            return $;
        }
    }

}
