// *** WARNING: this file was generated by pulumi-language-java. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.docker.inputs;

import com.pulumi.core.Output;
import com.pulumi.core.annotations.Import;
import com.pulumi.exceptions.MissingRequiredPropertyException;
import java.lang.Integer;
import java.lang.String;
import java.util.Objects;
import java.util.Optional;
import javax.annotation.Nullable;


public final class ServiceEndpointSpecPortArgs extends com.pulumi.resources.ResourceArgs {

    public static final ServiceEndpointSpecPortArgs Empty = new ServiceEndpointSpecPortArgs();

    /**
     * A random name for the port
     * 
     */
    @Import(name="name")
    private @Nullable Output<String> name;

    /**
     * @return A random name for the port
     * 
     */
    public Optional<Output<String>> name() {
        return Optional.ofNullable(this.name);
    }

    /**
     * Rrepresents the protocol of a port: `tcp`, `udp` or `sctp`. Defaults to `tcp`.
     * 
     */
    @Import(name="protocol")
    private @Nullable Output<String> protocol;

    /**
     * @return Rrepresents the protocol of a port: `tcp`, `udp` or `sctp`. Defaults to `tcp`.
     * 
     */
    public Optional<Output<String>> protocol() {
        return Optional.ofNullable(this.protocol);
    }

    /**
     * Represents the mode in which the port is to be published: &#39;ingress&#39; or &#39;host&#39;. Defaults to `ingress`.
     * 
     */
    @Import(name="publishMode")
    private @Nullable Output<String> publishMode;

    /**
     * @return Represents the mode in which the port is to be published: &#39;ingress&#39; or &#39;host&#39;. Defaults to `ingress`.
     * 
     */
    public Optional<Output<String>> publishMode() {
        return Optional.ofNullable(this.publishMode);
    }

    /**
     * The port on the swarm hosts
     * 
     */
    @Import(name="publishedPort")
    private @Nullable Output<Integer> publishedPort;

    /**
     * @return The port on the swarm hosts
     * 
     */
    public Optional<Output<Integer>> publishedPort() {
        return Optional.ofNullable(this.publishedPort);
    }

    /**
     * The port inside the container
     * 
     */
    @Import(name="targetPort", required=true)
    private Output<Integer> targetPort;

    /**
     * @return The port inside the container
     * 
     */
    public Output<Integer> targetPort() {
        return this.targetPort;
    }

    private ServiceEndpointSpecPortArgs() {}

    private ServiceEndpointSpecPortArgs(ServiceEndpointSpecPortArgs $) {
        this.name = $.name;
        this.protocol = $.protocol;
        this.publishMode = $.publishMode;
        this.publishedPort = $.publishedPort;
        this.targetPort = $.targetPort;
    }

    public static Builder builder() {
        return new Builder();
    }
    public static Builder builder(ServiceEndpointSpecPortArgs defaults) {
        return new Builder(defaults);
    }

    public static final class Builder {
        private ServiceEndpointSpecPortArgs $;

        public Builder() {
            $ = new ServiceEndpointSpecPortArgs();
        }

        public Builder(ServiceEndpointSpecPortArgs defaults) {
            $ = new ServiceEndpointSpecPortArgs(Objects.requireNonNull(defaults));
        }

        /**
         * @param name A random name for the port
         * 
         * @return builder
         * 
         */
        public Builder name(@Nullable Output<String> name) {
            $.name = name;
            return this;
        }

        /**
         * @param name A random name for the port
         * 
         * @return builder
         * 
         */
        public Builder name(String name) {
            return name(Output.of(name));
        }

        /**
         * @param protocol Rrepresents the protocol of a port: `tcp`, `udp` or `sctp`. Defaults to `tcp`.
         * 
         * @return builder
         * 
         */
        public Builder protocol(@Nullable Output<String> protocol) {
            $.protocol = protocol;
            return this;
        }

        /**
         * @param protocol Rrepresents the protocol of a port: `tcp`, `udp` or `sctp`. Defaults to `tcp`.
         * 
         * @return builder
         * 
         */
        public Builder protocol(String protocol) {
            return protocol(Output.of(protocol));
        }

        /**
         * @param publishMode Represents the mode in which the port is to be published: &#39;ingress&#39; or &#39;host&#39;. Defaults to `ingress`.
         * 
         * @return builder
         * 
         */
        public Builder publishMode(@Nullable Output<String> publishMode) {
            $.publishMode = publishMode;
            return this;
        }

        /**
         * @param publishMode Represents the mode in which the port is to be published: &#39;ingress&#39; or &#39;host&#39;. Defaults to `ingress`.
         * 
         * @return builder
         * 
         */
        public Builder publishMode(String publishMode) {
            return publishMode(Output.of(publishMode));
        }

        /**
         * @param publishedPort The port on the swarm hosts
         * 
         * @return builder
         * 
         */
        public Builder publishedPort(@Nullable Output<Integer> publishedPort) {
            $.publishedPort = publishedPort;
            return this;
        }

        /**
         * @param publishedPort The port on the swarm hosts
         * 
         * @return builder
         * 
         */
        public Builder publishedPort(Integer publishedPort) {
            return publishedPort(Output.of(publishedPort));
        }

        /**
         * @param targetPort The port inside the container
         * 
         * @return builder
         * 
         */
        public Builder targetPort(Output<Integer> targetPort) {
            $.targetPort = targetPort;
            return this;
        }

        /**
         * @param targetPort The port inside the container
         * 
         * @return builder
         * 
         */
        public Builder targetPort(Integer targetPort) {
            return targetPort(Output.of(targetPort));
        }

        public ServiceEndpointSpecPortArgs build() {
            if ($.targetPort == null) {
                throw new MissingRequiredPropertyException("ServiceEndpointSpecPortArgs", "targetPort");
            }
            return $;
        }
    }

}
