// *** WARNING: this file was generated by pulumi-java-gen. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.docker.inputs;

import com.pulumi.core.Output;
import com.pulumi.core.annotations.Import;
import java.lang.Integer;
import java.lang.String;
import java.util.Objects;
import java.util.Optional;
import javax.annotation.Nullable;


public final class ServiceTaskSpecContainerSpecSecretArgs extends com.pulumi.resources.ResourceArgs {

    public static final ServiceTaskSpecContainerSpecSecretArgs Empty = new ServiceTaskSpecContainerSpecSecretArgs();

    @Import(name="fileGid")
    private @Nullable Output<String> fileGid;

    public Optional<Output<String>> fileGid() {
        return Optional.ofNullable(this.fileGid);
    }

    @Import(name="fileMode")
    private @Nullable Output<Integer> fileMode;

    public Optional<Output<Integer>> fileMode() {
        return Optional.ofNullable(this.fileMode);
    }

    @Import(name="fileName", required=true)
    private Output<String> fileName;

    public Output<String> fileName() {
        return this.fileName;
    }

    @Import(name="fileUid")
    private @Nullable Output<String> fileUid;

    public Optional<Output<String>> fileUid() {
        return Optional.ofNullable(this.fileUid);
    }

    @Import(name="secretId", required=true)
    private Output<String> secretId;

    public Output<String> secretId() {
        return this.secretId;
    }

    @Import(name="secretName")
    private @Nullable Output<String> secretName;

    public Optional<Output<String>> secretName() {
        return Optional.ofNullable(this.secretName);
    }

    private ServiceTaskSpecContainerSpecSecretArgs() {}

    private ServiceTaskSpecContainerSpecSecretArgs(ServiceTaskSpecContainerSpecSecretArgs $) {
        this.fileGid = $.fileGid;
        this.fileMode = $.fileMode;
        this.fileName = $.fileName;
        this.fileUid = $.fileUid;
        this.secretId = $.secretId;
        this.secretName = $.secretName;
    }

    public static Builder builder() {
        return new Builder();
    }
    public static Builder builder(ServiceTaskSpecContainerSpecSecretArgs defaults) {
        return new Builder(defaults);
    }

    public static final class Builder {
        private ServiceTaskSpecContainerSpecSecretArgs $;

        public Builder() {
            $ = new ServiceTaskSpecContainerSpecSecretArgs();
        }

        public Builder(ServiceTaskSpecContainerSpecSecretArgs defaults) {
            $ = new ServiceTaskSpecContainerSpecSecretArgs(Objects.requireNonNull(defaults));
        }

        public Builder fileGid(@Nullable Output<String> fileGid) {
            $.fileGid = fileGid;
            return this;
        }

        public Builder fileGid(String fileGid) {
            return fileGid(Output.of(fileGid));
        }

        public Builder fileMode(@Nullable Output<Integer> fileMode) {
            $.fileMode = fileMode;
            return this;
        }

        public Builder fileMode(Integer fileMode) {
            return fileMode(Output.of(fileMode));
        }

        public Builder fileName(Output<String> fileName) {
            $.fileName = fileName;
            return this;
        }

        public Builder fileName(String fileName) {
            return fileName(Output.of(fileName));
        }

        public Builder fileUid(@Nullable Output<String> fileUid) {
            $.fileUid = fileUid;
            return this;
        }

        public Builder fileUid(String fileUid) {
            return fileUid(Output.of(fileUid));
        }

        public Builder secretId(Output<String> secretId) {
            $.secretId = secretId;
            return this;
        }

        public Builder secretId(String secretId) {
            return secretId(Output.of(secretId));
        }

        public Builder secretName(@Nullable Output<String> secretName) {
            $.secretName = secretName;
            return this;
        }

        public Builder secretName(String secretName) {
            return secretName(Output.of(secretName));
        }

        public ServiceTaskSpecContainerSpecSecretArgs build() {
            $.fileName = Objects.requireNonNull($.fileName, "expected parameter 'fileName' to be non-null");
            $.secretId = Objects.requireNonNull($.secretId, "expected parameter 'secretId' to be non-null");
            return $;
        }
    }

}
