// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Docker.Outputs
{

    [OutputType]
    public sealed class ContainerNetworksAdvanced
    {
        /// <summary>
        /// The network aliases of the container in the specific network.
        /// </summary>
        public readonly ImmutableArray<string> Aliases;
        /// <summary>
        /// The IPV4 address of the container in the specific network.
        /// </summary>
        public readonly string? Ipv4Address;
        /// <summary>
        /// The IPV6 address of the container in the specific network.
        /// </summary>
        public readonly string? Ipv6Address;
        /// <summary>
        /// The name or id of the network to use. You can use `Name` or `Id` attribute from a `docker.Network` resource.
        /// </summary>
        public readonly string Name;

        [OutputConstructor]
        private ContainerNetworksAdvanced(
            ImmutableArray<string> aliases,

            string? ipv4Address,

            string? ipv6Address,

            string name)
        {
            Aliases = aliases;
            Ipv4Address = ipv4Address;
            Ipv6Address = ipv6Address;
            Name = name;
        }
    }
}
