// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Docker.Outputs
{

    [OutputType]
    public sealed class ContainerCapabilities
    {
        /// <summary>
        /// list of linux capabilities to add.
        /// </summary>
        public readonly ImmutableArray<string> Adds;
        /// <summary>
        /// list of linux capabilities to drop.
        /// </summary>
        public readonly ImmutableArray<string> Drops;

        [OutputConstructor]
        private ContainerCapabilities(
            ImmutableArray<string> adds,

            ImmutableArray<string> drops)
        {
            Adds = adds;
            Drops = drops;
        }
    }
}
