// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Docker.Outputs
{

    [OutputType]
    public sealed class RegistryImageBuildAuthConfig
    {
        public readonly string? Auth;
        public readonly string? Email;
        public readonly string HostName;
        public readonly string? IdentityToken;
        public readonly string? Password;
        public readonly string? RegistryToken;
        public readonly string? ServerAddress;
        public readonly string? UserName;

        [OutputConstructor]
        private RegistryImageBuildAuthConfig(
            string? auth,

            string? email,

            string hostName,

            string? identityToken,

            string? password,

            string? registryToken,

            string? serverAddress,

            string? userName)
        {
            Auth = auth;
            Email = email;
            HostName = hostName;
            IdentityToken = identityToken;
            Password = password;
            RegistryToken = registryToken;
            ServerAddress = serverAddress;
            UserName = userName;
        }
    }
}
