// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Docker.Outputs
{

    [OutputType]
    public sealed class ServiceEndpointSpec
    {
        public readonly string? Mode;
        public readonly ImmutableArray<Outputs.ServiceEndpointSpecPort> Ports;

        [OutputConstructor]
        private ServiceEndpointSpec(
            string? mode,

            ImmutableArray<Outputs.ServiceEndpointSpecPort> ports)
        {
            Mode = mode;
            Ports = ports;
        }
    }
}
