// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Docker.Outputs
{

    [OutputType]
    public sealed class ServiceUpdateConfig
    {
        /// <summary>
        /// Delay between task updates `(ns|us|ms|s|m|h)`. Defaults to `0s`.
        /// </summary>
        public readonly string? Delay;
        /// <summary>
        /// Action on update failure: `pause`, `continue` or `rollback`. Defaults to `pause`.
        /// </summary>
        public readonly string? FailureAction;
        /// <summary>
        /// Failure rate to tolerate during an update. Defaults to `0.0`.
        /// </summary>
        public readonly string? MaxFailureRatio;
        /// <summary>
        /// Duration after each task update to monitor for failure (ns|us|ms|s|m|h). Defaults to `5s`.
        /// </summary>
        public readonly string? Monitor;
        /// <summary>
        /// Update order: either 'stop-first' or 'start-first'. Defaults to `stop-first`.
        /// </summary>
        public readonly string? Order;
        /// <summary>
        /// Maximum number of tasks to be updated in one iteration. Defaults to `1`
        /// </summary>
        public readonly int? Parallelism;

        [OutputConstructor]
        private ServiceUpdateConfig(
            string? delay,

            string? failureAction,

            string? maxFailureRatio,

            string? monitor,

            string? order,

            int? parallelism)
        {
            Delay = delay;
            FailureAction = failureAction;
            MaxFailureRatio = maxFailureRatio;
            Monitor = monitor;
            Order = order;
            Parallelism = parallelism;
        }
    }
}
