// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Docker.Outputs
{

    [OutputType]
    public sealed class ServiceEndpointSpecPort
    {
        /// <summary>
        /// A random name for the port
        /// </summary>
        public readonly string? Name;
        /// <summary>
        /// Rrepresents the protocol of a port: `Tcp`, `Udp` or `Sctp`. Defaults to `Tcp`.
        /// </summary>
        public readonly string? Protocol;
        /// <summary>
        /// Represents the mode in which the port is to be published: 'ingress' or 'host'. Defaults to `Ingress`.
        /// </summary>
        public readonly string? PublishMode;
        /// <summary>
        /// The port on the swarm hosts
        /// </summary>
        public readonly int? PublishedPort;
        /// <summary>
        /// The port inside the container
        /// </summary>
        public readonly int TargetPort;

        [OutputConstructor]
        private ServiceEndpointSpecPort(
            string? name,

            string? protocol,

            string? publishMode,

            int? publishedPort,

            int targetPort)
        {
            Name = name;
            Protocol = protocol;
            PublishMode = publishMode;
            PublishedPort = publishedPort;
            TargetPort = targetPort;
        }
    }
}
