// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package config

import (
	"context"
	"reflect"

	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

type RegistryAuth struct {
	Address           string  `pulumi:"address"`
	ConfigFile        *string `pulumi:"configFile"`
	ConfigFileContent *string `pulumi:"configFileContent"`
	Password          *string `pulumi:"password"`
	Username          *string `pulumi:"username"`
}

// RegistryAuthInput is an input type that accepts RegistryAuthArgs and RegistryAuthOutput values.
// You can construct a concrete instance of `RegistryAuthInput` via:
//
//          RegistryAuthArgs{...}
type RegistryAuthInput interface {
	pulumi.Input

	ToRegistryAuthOutput() RegistryAuthOutput
	ToRegistryAuthOutputWithContext(context.Context) RegistryAuthOutput
}

type RegistryAuthArgs struct {
	Address           pulumi.StringInput    `pulumi:"address"`
	ConfigFile        pulumi.StringPtrInput `pulumi:"configFile"`
	ConfigFileContent pulumi.StringPtrInput `pulumi:"configFileContent"`
	Password          pulumi.StringPtrInput `pulumi:"password"`
	Username          pulumi.StringPtrInput `pulumi:"username"`
}

func (RegistryAuthArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*RegistryAuth)(nil)).Elem()
}

func (i RegistryAuthArgs) ToRegistryAuthOutput() RegistryAuthOutput {
	return i.ToRegistryAuthOutputWithContext(context.Background())
}

func (i RegistryAuthArgs) ToRegistryAuthOutputWithContext(ctx context.Context) RegistryAuthOutput {
	return pulumi.ToOutputWithContext(ctx, i).(RegistryAuthOutput)
}

type RegistryAuthOutput struct{ *pulumi.OutputState }

func (RegistryAuthOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*RegistryAuth)(nil)).Elem()
}

func (o RegistryAuthOutput) ToRegistryAuthOutput() RegistryAuthOutput {
	return o
}

func (o RegistryAuthOutput) ToRegistryAuthOutputWithContext(ctx context.Context) RegistryAuthOutput {
	return o
}

func (o RegistryAuthOutput) Address() pulumi.StringOutput {
	return o.ApplyT(func(v RegistryAuth) string { return v.Address }).(pulumi.StringOutput)
}

func (o RegistryAuthOutput) ConfigFile() pulumi.StringPtrOutput {
	return o.ApplyT(func(v RegistryAuth) *string { return v.ConfigFile }).(pulumi.StringPtrOutput)
}

func (o RegistryAuthOutput) ConfigFileContent() pulumi.StringPtrOutput {
	return o.ApplyT(func(v RegistryAuth) *string { return v.ConfigFileContent }).(pulumi.StringPtrOutput)
}

func (o RegistryAuthOutput) Password() pulumi.StringPtrOutput {
	return o.ApplyT(func(v RegistryAuth) *string { return v.Password }).(pulumi.StringPtrOutput)
}

func (o RegistryAuthOutput) Username() pulumi.StringPtrOutput {
	return o.ApplyT(func(v RegistryAuth) *string { return v.Username }).(pulumi.StringPtrOutput)
}

func init() {
	pulumi.RegisterOutputType(RegistryAuthOutput{})
}
