// *** WARNING: this file was generated by pulumi-java-gen. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.docker.buildx.inputs;

import com.pulumi.core.Output;
import com.pulumi.core.annotations.Import;
import com.pulumi.exceptions.MissingRequiredPropertyException;
import java.lang.String;
import java.util.Objects;


public final class ContextArgs extends com.pulumi.resources.ResourceArgs {

    public static final ContextArgs Empty = new ContextArgs();

    /**
     * Resources to use for build context.
     * 
     * The location can be:
     * * A relative or absolute path to a local directory (`.`, `./app`,
     *   `/app`, etc.).
     * * A remote URL of a Git repository, tarball, or plain text file
     *   (`https://github.com/user/myrepo.git`, `http://server/context.tar.gz`,
     *   etc.).
     * 
     */
    @Import(name="location", required=true)
    private Output<String> location;

    /**
     * @return Resources to use for build context.
     * 
     * The location can be:
     * * A relative or absolute path to a local directory (`.`, `./app`,
     *   `/app`, etc.).
     * * A remote URL of a Git repository, tarball, or plain text file
     *   (`https://github.com/user/myrepo.git`, `http://server/context.tar.gz`,
     *   etc.).
     * 
     */
    public Output<String> location() {
        return this.location;
    }

    private ContextArgs() {}

    private ContextArgs(ContextArgs $) {
        this.location = $.location;
    }

    public static Builder builder() {
        return new Builder();
    }
    public static Builder builder(ContextArgs defaults) {
        return new Builder(defaults);
    }

    public static final class Builder {
        private ContextArgs $;

        public Builder() {
            $ = new ContextArgs();
        }

        public Builder(ContextArgs defaults) {
            $ = new ContextArgs(Objects.requireNonNull(defaults));
        }

        /**
         * @param location Resources to use for build context.
         * 
         * The location can be:
         * * A relative or absolute path to a local directory (`.`, `./app`,
         *   `/app`, etc.).
         * * A remote URL of a Git repository, tarball, or plain text file
         *   (`https://github.com/user/myrepo.git`, `http://server/context.tar.gz`,
         *   etc.).
         * 
         * @return builder
         * 
         */
        public Builder location(Output<String> location) {
            $.location = location;
            return this;
        }

        /**
         * @param location Resources to use for build context.
         * 
         * The location can be:
         * * A relative or absolute path to a local directory (`.`, `./app`,
         *   `/app`, etc.).
         * * A remote URL of a Git repository, tarball, or plain text file
         *   (`https://github.com/user/myrepo.git`, `http://server/context.tar.gz`,
         *   etc.).
         * 
         * @return builder
         * 
         */
        public Builder location(String location) {
            return location(Output.of(location));
        }

        public ContextArgs build() {
            if ($.location == null) {
                throw new MissingRequiredPropertyException("ContextArgs", "location");
            }
            return $;
        }
    }

}
