// *** WARNING: this file was generated by pulumi-java-gen. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.docker.buildx.inputs;

import com.pulumi.core.Output;
import com.pulumi.core.annotations.Import;
import com.pulumi.exceptions.MissingRequiredPropertyException;
import java.lang.String;
import java.util.Objects;


public final class ExportTarArgs extends com.pulumi.resources.ResourceArgs {

    public static final ExportTarArgs Empty = new ExportTarArgs();

    /**
     * Output path.
     * 
     */
    @Import(name="dest", required=true)
    private Output<String> dest;

    /**
     * @return Output path.
     * 
     */
    public Output<String> dest() {
        return this.dest;
    }

    private ExportTarArgs() {}

    private ExportTarArgs(ExportTarArgs $) {
        this.dest = $.dest;
    }

    public static Builder builder() {
        return new Builder();
    }
    public static Builder builder(ExportTarArgs defaults) {
        return new Builder(defaults);
    }

    public static final class Builder {
        private ExportTarArgs $;

        public Builder() {
            $ = new ExportTarArgs();
        }

        public Builder(ExportTarArgs defaults) {
            $ = new ExportTarArgs(Objects.requireNonNull(defaults));
        }

        /**
         * @param dest Output path.
         * 
         * @return builder
         * 
         */
        public Builder dest(Output<String> dest) {
            $.dest = dest;
            return this;
        }

        /**
         * @param dest Output path.
         * 
         * @return builder
         * 
         */
        public Builder dest(String dest) {
            return dest(Output.of(dest));
        }

        public ExportTarArgs build() {
            if ($.dest == null) {
                throw new MissingRequiredPropertyException("ExportTarArgs", "dest");
            }
            return $;
        }
    }

}
