package provider

const (
	lintArgs            = "args"
	lintAuthConfigs     = "authConfigs"
	lintBaseImageName   = "baseImageName"
	lintBuild           = "build"
	lintBuilderBuildKit = "BuilderBuildKit"
	lintBuilderV1       = "BuilderV1"
	lintBuildOnPreview  = "buildOnPreview"
	lintCAMaterial      = "caMaterial"
	lintCacheFrom       = "cacheFrom"
	lintContext         = "context"
	lintCustomIgnore    = "customignore"
	lintDigest          = "Digest"
	lintDockerfile      = "dockerfile"
	lintDockerignore    = ".dockerignore"
	lintFledge          = "Fledge"
	lintFooDockerfile   = "./foo/Dockerfile"
	lintHost            = "host"
	lintImageName       = "imageName"
	lintImages          = "images"
	lintObject          = "object"
	lintPassword        = "password"
	lintPlatform        = "platform"
	lintPulumipus       = "pulumipus"
	lintRawCAString     = "raw-ca-string"
	lintRegistry        = "registry"
	lintRegistryServer  = "registryServer"
	lintServer          = "server"
	lintSkipPush        = "skipPush"
	lintStringType      = "string"
	lintSwiftwind       = "Swiftwind"
	lintTestCAMaterial  = "materialsareweird"
	lintTestHost        = "thisisatesthost"
	lintTestRawCert     = "raw-cert-string"
	lintTestRootIgnore  = "rootignore"
	lintUsername        = "username"
)
