// *** WARNING: this file was generated by pulumi-language-java. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.docker;

import com.pulumi.core.Output;
import com.pulumi.core.annotations.Import;
import com.pulumi.docker.inputs.RegistryImageAuthConfigArgs;
import com.pulumi.docker.inputs.RegistryImageBuildArgs;
import java.lang.Boolean;
import java.lang.String;
import java.util.Map;
import java.util.Objects;
import java.util.Optional;
import javax.annotation.Nullable;


public final class RegistryImageArgs extends com.pulumi.resources.ResourceArgs {

    public static final RegistryImageArgs Empty = new RegistryImageArgs();

    /**
     * Authentication configuration for the Docker registry. It is only used for this resource.
     * 
     */
    @Import(name="authConfig")
    private @Nullable Output<RegistryImageAuthConfigArgs> authConfig;

    /**
     * @return Authentication configuration for the Docker registry. It is only used for this resource.
     * 
     */
    public Optional<Output<RegistryImageAuthConfigArgs>> authConfig() {
        return Optional.ofNullable(this.authConfig);
    }

    /**
     * Configuration to build an image. Requires the `Use containerd for pulling and storing images` option to be disabled in the Docker Host(https://github.com/kreuzwerker/terraform-provider-docker/issues/534). Please see [docker build command reference](https://docs.docker.com/engine/reference/commandline/build/#options) too.
     * 
     */
    @Import(name="build")
    private @Nullable Output<RegistryImageBuildArgs> build;

    /**
     * @return Configuration to build an image. Requires the `Use containerd for pulling and storing images` option to be disabled in the Docker Host(https://github.com/kreuzwerker/terraform-provider-docker/issues/534). Please see [docker build command reference](https://docs.docker.com/engine/reference/commandline/build/#options) too.
     * 
     */
    public Optional<Output<RegistryImageBuildArgs>> build() {
        return Optional.ofNullable(this.build);
    }

    /**
     * If `true`, the verification of TLS certificates of the server/registry is disabled. Defaults to `false`
     * 
     */
    @Import(name="insecureSkipVerify")
    private @Nullable Output<Boolean> insecureSkipVerify;

    /**
     * @return If `true`, the verification of TLS certificates of the server/registry is disabled. Defaults to `false`
     * 
     */
    public Optional<Output<Boolean>> insecureSkipVerify() {
        return Optional.ofNullable(this.insecureSkipVerify);
    }

    /**
     * If true, then the Docker image won&#39;t be deleted on destroy operation. If this is false, it will delete the image from the docker registry on destroy operation. Defaults to `false`
     * 
     */
    @Import(name="keepRemotely")
    private @Nullable Output<Boolean> keepRemotely;

    /**
     * @return If true, then the Docker image won&#39;t be deleted on destroy operation. If this is false, it will delete the image from the docker registry on destroy operation. Defaults to `false`
     * 
     */
    public Optional<Output<Boolean>> keepRemotely() {
        return Optional.ofNullable(this.keepRemotely);
    }

    /**
     * The name of the Docker image.
     * 
     */
    @Import(name="name")
    private @Nullable Output<String> name;

    /**
     * @return The name of the Docker image.
     * 
     */
    public Optional<Output<String>> name() {
        return Optional.ofNullable(this.name);
    }

    /**
     * A map of arbitrary strings that, when changed, will force the `docker.RegistryImage` resource to be replaced. This can be used to repush a local image
     * 
     */
    @Import(name="triggers")
    private @Nullable Output<Map<String,String>> triggers;

    /**
     * @return A map of arbitrary strings that, when changed, will force the `docker.RegistryImage` resource to be replaced. This can be used to repush a local image
     * 
     */
    public Optional<Output<Map<String,String>>> triggers() {
        return Optional.ofNullable(this.triggers);
    }

    private RegistryImageArgs() {}

    private RegistryImageArgs(RegistryImageArgs $) {
        this.authConfig = $.authConfig;
        this.build = $.build;
        this.insecureSkipVerify = $.insecureSkipVerify;
        this.keepRemotely = $.keepRemotely;
        this.name = $.name;
        this.triggers = $.triggers;
    }

    public static Builder builder() {
        return new Builder();
    }
    public static Builder builder(RegistryImageArgs defaults) {
        return new Builder(defaults);
    }

    public static final class Builder {
        private RegistryImageArgs $;

        public Builder() {
            $ = new RegistryImageArgs();
        }

        public Builder(RegistryImageArgs defaults) {
            $ = new RegistryImageArgs(Objects.requireNonNull(defaults));
        }

        /**
         * @param authConfig Authentication configuration for the Docker registry. It is only used for this resource.
         * 
         * @return builder
         * 
         */
        public Builder authConfig(@Nullable Output<RegistryImageAuthConfigArgs> authConfig) {
            $.authConfig = authConfig;
            return this;
        }

        /**
         * @param authConfig Authentication configuration for the Docker registry. It is only used for this resource.
         * 
         * @return builder
         * 
         */
        public Builder authConfig(RegistryImageAuthConfigArgs authConfig) {
            return authConfig(Output.of(authConfig));
        }

        /**
         * @param build Configuration to build an image. Requires the `Use containerd for pulling and storing images` option to be disabled in the Docker Host(https://github.com/kreuzwerker/terraform-provider-docker/issues/534). Please see [docker build command reference](https://docs.docker.com/engine/reference/commandline/build/#options) too.
         * 
         * @return builder
         * 
         */
        public Builder build(@Nullable Output<RegistryImageBuildArgs> build) {
            $.build = build;
            return this;
        }

        /**
         * @param build Configuration to build an image. Requires the `Use containerd for pulling and storing images` option to be disabled in the Docker Host(https://github.com/kreuzwerker/terraform-provider-docker/issues/534). Please see [docker build command reference](https://docs.docker.com/engine/reference/commandline/build/#options) too.
         * 
         * @return builder
         * 
         */
        public Builder build(RegistryImageBuildArgs build) {
            return build(Output.of(build));
        }

        /**
         * @param insecureSkipVerify If `true`, the verification of TLS certificates of the server/registry is disabled. Defaults to `false`
         * 
         * @return builder
         * 
         */
        public Builder insecureSkipVerify(@Nullable Output<Boolean> insecureSkipVerify) {
            $.insecureSkipVerify = insecureSkipVerify;
            return this;
        }

        /**
         * @param insecureSkipVerify If `true`, the verification of TLS certificates of the server/registry is disabled. Defaults to `false`
         * 
         * @return builder
         * 
         */
        public Builder insecureSkipVerify(Boolean insecureSkipVerify) {
            return insecureSkipVerify(Output.of(insecureSkipVerify));
        }

        /**
         * @param keepRemotely If true, then the Docker image won&#39;t be deleted on destroy operation. If this is false, it will delete the image from the docker registry on destroy operation. Defaults to `false`
         * 
         * @return builder
         * 
         */
        public Builder keepRemotely(@Nullable Output<Boolean> keepRemotely) {
            $.keepRemotely = keepRemotely;
            return this;
        }

        /**
         * @param keepRemotely If true, then the Docker image won&#39;t be deleted on destroy operation. If this is false, it will delete the image from the docker registry on destroy operation. Defaults to `false`
         * 
         * @return builder
         * 
         */
        public Builder keepRemotely(Boolean keepRemotely) {
            return keepRemotely(Output.of(keepRemotely));
        }

        /**
         * @param name The name of the Docker image.
         * 
         * @return builder
         * 
         */
        public Builder name(@Nullable Output<String> name) {
            $.name = name;
            return this;
        }

        /**
         * @param name The name of the Docker image.
         * 
         * @return builder
         * 
         */
        public Builder name(String name) {
            return name(Output.of(name));
        }

        /**
         * @param triggers A map of arbitrary strings that, when changed, will force the `docker.RegistryImage` resource to be replaced. This can be used to repush a local image
         * 
         * @return builder
         * 
         */
        public Builder triggers(@Nullable Output<Map<String,String>> triggers) {
            $.triggers = triggers;
            return this;
        }

        /**
         * @param triggers A map of arbitrary strings that, when changed, will force the `docker.RegistryImage` resource to be replaced. This can be used to repush a local image
         * 
         * @return builder
         * 
         */
        public Builder triggers(Map<String,String> triggers) {
            return triggers(Output.of(triggers));
        }

        public RegistryImageArgs build() {
            return $;
        }
    }

}
