// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Docker.Inputs
{

    public sealed class ContainerMountVolumeOptionsGetArgs : Pulumi.ResourceArgs
    {
        [Input("driverName")]
        public Input<string>? DriverName { get; set; }

        [Input("driverOptions")]
        private InputMap<string>? _driverOptions;
        public InputMap<string> DriverOptions
        {
            get => _driverOptions ?? (_driverOptions = new InputMap<string>());
            set => _driverOptions = value;
        }

        [Input("labels")]
        private InputList<Inputs.ContainerMountVolumeOptionsLabelGetArgs>? _labels;
        public InputList<Inputs.ContainerMountVolumeOptionsLabelGetArgs> Labels
        {
            get => _labels ?? (_labels = new InputList<Inputs.ContainerMountVolumeOptionsLabelGetArgs>());
            set => _labels = value;
        }

        [Input("noCopy")]
        public Input<bool>? NoCopy { get; set; }

        public ContainerMountVolumeOptionsGetArgs()
        {
        }
    }
}
