// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Docker.Inputs
{

    public sealed class ServiceTaskSpecPlacementArgs : Pulumi.ResourceArgs
    {
        [Input("constraints")]
        private InputList<string>? _constraints;
        public InputList<string> Constraints
        {
            get => _constraints ?? (_constraints = new InputList<string>());
            set => _constraints = value;
        }

        [Input("platforms")]
        private InputList<Inputs.ServiceTaskSpecPlacementPlatformArgs>? _platforms;
        public InputList<Inputs.ServiceTaskSpecPlacementPlatformArgs> Platforms
        {
            get => _platforms ?? (_platforms = new InputList<Inputs.ServiceTaskSpecPlacementPlatformArgs>());
            set => _platforms = value;
        }

        [Input("prefs")]
        private InputList<string>? _prefs;
        public InputList<string> Prefs
        {
            get => _prefs ?? (_prefs = new InputList<string>());
            set => _prefs = value;
        }

        public ServiceTaskSpecPlacementArgs()
        {
        }
    }
}
