// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Docker.Inputs
{

    public sealed class ServiceEndpointSpecGetArgs : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// The mode of resolution to use for internal load balancing between tasks
        /// </summary>
        [Input("mode")]
        public Input<string>? Mode { get; set; }

        [Input("ports")]
        private InputList<Inputs.ServiceEndpointSpecPortGetArgs>? _ports;

        /// <summary>
        /// List of exposed ports that this service is accessible on from the outside. Ports can only be provided if 'vip' resolution mode is used
        /// </summary>
        public InputList<Inputs.ServiceEndpointSpecPortGetArgs> Ports
        {
            get => _ports ?? (_ports = new InputList<Inputs.ServiceEndpointSpecPortGetArgs>());
            set => _ports = value;
        }

        public ServiceEndpointSpecGetArgs()
        {
        }
        public static new ServiceEndpointSpecGetArgs Empty => new ServiceEndpointSpecGetArgs();
    }
}
